### ISSUE TITLE
Not working on Fedora 36

### ISSUE THREAD

**Issue by abcfy2** [userdocs/qbittorrent-nox-static#97]
From issue: https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/400

```sh
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  context: unknown option (digital envelope routines) [asio.ssl:50331817]
```

And your latest build also contains this issue.

I can reproduce in Fedora environment.

I try to find out the reason, and I find this might be some configs issues in Fedora `openssl.cnf`, but I don't know which setting caused this issue.

After remove `openssl.cnf` will work:

```sh
$ sudo mv /etc/ssl/openssl.cnf /etc/ssl/openssl.cnf.bak
```

Would you please help?

**Comment by userdocs** [comment]
I have so far been only able to get this

```
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  context: unknown option (digital envelope routines) [asio.ssl:50331817]

Program received signal SIGABRT, Aborted.
0x00007ffff55c66e9 in __restore_sigs ()
(gdb) backtrace
#0  0x00007ffff55c66e9 in __restore_sigs ()
#1  0x00007ffff55c6742 in raise ()
#2  0x00007ffff55c71be in __stdio_write ()
#3  0x00007ffff7ffd098 in buf ()
#4  0x0000000000000000 in ?? ()
```

I'll investigate further to see if there is anything i can point to.

**Comment by userdocs** [comment]
I'm thinking it's related to this package but i need to look into it more.

https://fedora.pkgs.org/36/fedora-updates-x86_64/openssl-3.0.5-1.fc36.x86_64.rpm.html

**Comment by userdocs** [comment]
It might not be specific to that package. Since i also can build glibc static i tried that is it failed bit the back trace might be more helpful

```
Program received signal SIGABRT, Aborted.
raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: Directory not empty.
(gdb) backtrace
#0  raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x0000000000473a33 in abort () at abort.c:79
#2  0x0000000000472152 in __gnu_cxx::__verbose_terminate_handler() [clone .cold] ()
#3  0x00000000012e72d6 in __cxxabiv1::__terminate(void (*)()) ()
#4  0x00000000012e7311 in std::terminate() ()
#5  0x00000000012e7435 in __cxa_throw ()
#6  0x0000000000408b34 in void boost::throw_exception<boost::system::system_error>(boost::system::system_error const&) ()
#7  0x0000000000701280 in boost::asio::detail::do_throw_error(boost::system::error_code const&, char const*) ()
#8  0x00000000007012d1 in boost::asio::detail::throw_error(boost::system::error_code const&, char const*) ()
#9  0x00000000006e2150 in libtorrent::aux::session_impl::session_impl(boost::asio::io_context&, libtorrent::settings_pack const&, std::function<std::unique_ptr<libtorrent::disk_interface, std::default_delete<libtorrent::disk_interface> > (boost::asio::io_context&, libtorrent::settings_interface const&, libtorrent::counters&)>, libtorrent::flags::bitfield_flag<unsigned char, libtorrent::session_flags_tag, void>) ()
#10 0x000000000069622c in libtorrent::session::start(libtorrent::flags::bitfield_flag<unsigned char, libtorrent::session_flags_tag, void>, libtorrent::session_params&&, boost::asio::io_context*) ()
#11 0x000000000069744d in libtorrent::session::session(libtorrent::session_params const&) ()
#12 0x00000000004e59aa in BitTorrent::Session::initializeNativeSession() ()
#13 0x00000000004f7672 in BitTorrent::Session::Session(QObject*) ()
#14 0x00000000004f83b7 in BitTorrent::Session::initInstance() ()
#15 0x0000000000485db2 in Application::exec(QList<QString> const&) ()
#16 0x00000000004749e1 in main ()
(gdb)
```
